[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5", features = ["password-hash", "std"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.32.0"
rusqlite = "0.38.0"
tokio = "1.48.0"
